### PR TITLE
Pushy support

### PR DESCRIPTION
**Pull request by charliewolf**
Some users (such as myself) don't use Google Play Services.
Some services such as [Fastmail](https://blog.fastmail.com/2015/07/08/fastmail-app-for-android-now-available-from-yandex-store/) have started implementing support for [Pushy](http://www.pushy.me) notifications which don't go through Google.

Here is a patch that does pushy registration if Play Services is unavailable. Note that I have tested registration works and notifications can be received. That said, obviously, there would need to be code on the IRCCloud server side to support this--however Pushy's API is nearly identical to Google's.

(I have no affiliation with Pushy, I just want to use IRCCloud on my phone without Play Services)

### CODE REVIEW

**Comment by graingert** [comment]
@charliewolf this needs a rebase

**Comment by c99koder** [comment]
We have plans to support using the app on devices that don't have Google Play Services installed

**Comment by graingert** [comment]
> We have plans

How exciting and mysterious, is there a GH issue describing them?

**Comment by c99koder** [comment]
Sorry, looks like I accidentally a word. We don't have plans to support this.

**Comment by graingert** [comment]
@c99koder seems a shame if it's only because of push notifications that google play services is required.

**Pull request closed without merging**
