### PR TITLE
Adjust api23+ status bar color for dawn theme

### PR DESCRIPTION
**Pull request by The0x539**
i have most likely violated the regulations of two dozen color palette agencies

### CODE REVIEW

**Comment by c99koder** [comment]
Attaching some screenshots for @jwheare to review

New status bar color:
new

Previous status bar color:
old

**Comment by jwheare** [comment]
What's going on here?

**Comment by The0x539** [comment]
A less blue status bar?

**Comment by jwheare** [comment]
Right, but why? Personal preference or some guideline violation?

**Comment by The0x539** [comment]
Somewhere in between. There's very little documentation of status bars for light+colored app bars, but the one picture there has what seems like matching or almost-matching saturation, where the current IRCCloud app bar is nearly-gray while its status bar is a fair bit more blue.

**Comment by jwheare** [comment]
The main guideline seems to just be that the status bar should be darker than the app bar, which the current one is.

https://material.io/guidelines/layout/structure.html#structure-system-bars

See lower right:


Closing because this change seems a little arbitrary. Sorry.

**Pull request closed without merging**
